config/routes.php
<?php

/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */
use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Core\Configure;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass('DashedRoute');

Router::scope('/admin', ['prefix' => 'admin'], function (RouteBuilder $routes) {
    $routes->connect('/ads/add/:category/', ['controller' => 'ads', 'action' => 'add'], ['category' => '[0-9]+']);
    $routes->connect('/ads/add/:category/:location/', ['controller' => 'ads', 'action' => 'add'], ['category' => '[0-9]+', 'location' => '[A-Za-z_]+',]);
    $routes->connect('/:controller/', []);

    $routes->fallbacks('DashedRoute');
});



Router::scope('/', function (RouteBuilder $routes) {

    $routes->extensions(['json', 'rss']);
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/:language', array('controller' => 'pages', 'action' => 'home'), ['language' => join('|', array_keys(Configure::read('Langs')))]);
    $routes->connect('/:language/search', ['controller' => 'news', 'action' => 'search'], ['language' => join('|', array_keys(Configure::read('Langs')))]);
    $routes->connect('/:language/contact-us', ['controller' => 'contacts', 'action' => 'contact-us', 1]);
    $routes->connect('/:language/suggestions', ['controller' => 'contacts', 'action' => 'contact-us', 2]);
    $routes->connect('/:language/content/*', array('controller' => 'pages', 'action' => 'view'), ['language' => join('|', array_keys(Configure::read('Langs')))]);
    $routes->connect('/:language/:controller', array(), ['language' => join('|', array_keys(Configure::read('Langs')))]);
    $routes->connect('/:language/:controller/:action/*', array(), ['language' => join('|', array_keys(Configure::read('Langs')))]);

    $routes->connect('/', ['controller' => 'Pages', 'action' => 'home']);
    $routes->connect('/contact-us', ['controller' => 'contacts', 'action' => 'contact-us', 1]);
    $routes->connect('/suggestions', ['controller' => 'contacts', 'action' => 'contact-us', 2]);
    $routes->connect('/search', ['controller' => 'news', 'action' => 'search']);
    $routes->connect('/admin', ['controller' => 'users', 'action' => 'login', 'prefix' => 'admin']);
    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
//    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - 
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks('DashedRoute');
//    $routes->fallbacks('SlugRoute');
});

/**
 * Load all plugin routes.  See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Entity/User.php
<?php

namespace App\Model\Entity;

use Cake\ORM\Entity;
use Cake\Auth\DefaultPasswordHasher;

/**
 * User Entity.
 *
 * @property int $id
 * @property string $username
 * @property string $password
 * @property string $role
 * @property \Cake\I18n\Time $created
 * @property \Cake\I18n\Time $updated
 */
class User extends Entity {

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        '*' => true,
        'id' => true,
    ];

    /**
     * Fields that are excluded from JSON an array versions of the entity.
     *
     * @var array
     */
    protected $_hidden = [
//        'password'
    ];

    protected function _setPassword($value) {
        $hasher = new DefaultPasswordHasher();
        return $hasher->hash($value);
    }

}

src/Model/Table/UsersTable.php
<?php

namespace App\Model\Table;

use App\Model\Entity\User;
use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Users Model
 *
 */
class UsersTable extends Table {

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config) {
        parent::initialize($config);

        $this->table('users');
        $this->belongsTo('Groups', ['foreignKey' => 'group_id']);
        $this->belongsTo('Writers', ['foreignKey' => 'writer_id']);
        $this->displayField('username');
        $this->primaryKey('id');
        $this->addBehavior('Timestamp');
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function beforeMarshal(\Cake\Event\Event $event, \ArrayObject $data, \ArrayObject $options) {
        if (!empty($data['password'])) {
            $this->validator()->add('passwd', [
                'compare' => [
                    'rule' => ['compareWith', 'password'],
                    'message' => __('Passwords do not match')
            ]]);
        } elseif (empty($data['password']) && !empty($data['id'])) {
            unset($data['password'], $data['passwd']);
            $this->validator()->allowEmpty('password')->allowEmpty('passwd');
        } elseif (empty($data['id'])) {
            $this->validator()->notEmpty('password', __('Required'))->notEmpty('passwd', __('Required'));
        }
//        debug()
    }

    public function validationDefault(Validator $validator) {
        $validator->integer('id')->allowEmpty('id', 'create');

        $validator->notBlank('username', __('Required', true))
                ->notEmpty('writer_id', __('Required', true));
        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules) {
        $rules->add($rules->isUnique(['username']));
        return $rules;
    }

}

src/Controller/Admin/UsersController.php
<?php

namespace App\Controller\Admin;

use App\Controller\AdminController;

/**
 * Users Controller
 *
 * @property \App\Model\Table\UsersTable $Users
 * @property \App\Model\Table\GroupsTable $Groups
 */
class UsersController extends AdminController {

    /**
     * Index method
     *
     * @return \Cake\Network\Response|null
     */
    public function initialize() {
        parent::initialize();
    }

    public function beforeFilter(\Cake\Event\Event $event) {
        parent::beforeFilter($event);

//        $this->Auth->allow('add');
    }

    public function login() {
        $this->viewBuilder()->layout('');

        if ($this->Auth->user()) {

            $this->redirect(array('controller' => 'pages', 'action' => 'dashboard'));
        }
        if ($this->request->is('post')) {

            $uuser = $this->Auth->identify();
//            debug($uuser);exit;
            if ($uuser) {

                $this->Auth->setUser($uuser);
                return $this->redirect($this->Auth->redirectUrl());
            }
            $this->Flash->error(__('Your username or password was incorrect.'));
        }

        $this->set('title_for_layout', __('login'));
    }

    public function logout() {
        $this->Flash->success(__('Good Bye'));
        $this->redirect($this->Auth->logout());
    }

    public function index() {
        $this->paginate = [
            'contain' => ['Groups']
        ];
        $uusers = $this->paginate($this->Users);
        $this->set(compact('uusers'));
        $this->set('_serialize', ['uusers']);
    }

    /**
     * View method
     *
     * @param string|null $id User id.
     * @return \Cake\Network\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null) {
        $uuser = $this->Users->get($id, [
            'contain' => []
        ]);

        $this->set('user', $uuser);
        $this->set('_serialize', ['user']);
    }

    /**
     * Add method
     *
     * @return \Cake\Network\Response|void Redirects on successful add, renders view otherwise.
     */
    public function add() {
        $uuser = $this->Users->newEntity();
        if ($this->request->is('post')) {
            $uuser = $this->Users->patchEntity($uuser, $this->request->data);
            if ($this->Users->save($uuser)) {
                $this->Flash->success(__('The user has been saved.'));
                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('The user could not be saved. Please, try again.'));
            }
        }
        $groups = $this->Users->Groups->find('list');
        $writers = $this->Users->Writers->find('list', ['valueField' => 'ar_title',
            'keyField' => 'id']);
        $this->set(compact('uuser', 'groups', 'writers'));
        $this->set('_serialize', ['uuser']);
    }

    /**
     * Edit method
     *
     * @param string|null $id User id.
     * @return \Cake\Network\Response|void Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null) {
        $uuser = $this->Users->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $uuser = $this->Users->patchEntity($uuser, $this->request->data);
            if ($this->Users->save($uuser)) {
                $this->Flash->success(__('The user has been saved.'));
                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('The user could not be saved. Please, try again.'));
            }
        }
        $groups = $this->Users->Groups->find('list');
        $writers = $this->Users->Writers->find('list', ['valueField' => 'ar_title',
            'keyField' => 'id']);
        $uuser->unsetProperty('password');
        $this->set(compact('uuser', 'groups', 'writers'));
        $this->set('_serialize', ['uuser']);
        $this->render('add');
    }

    /**
     * Delete method
     *
     * @param string|null $id User id.
     * @return \Cake\Network\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null) {
//        $this->request->allowMethod(['post', 'delete']);
        $uuser = $this->Users->get($id);
        if ($this->Users->delete($uuser)) {
            $this->Flash->success(__('The user has been deleted.'));
        } else {
            $this->Flash->error(__('The user could not be deleted. Please, try again.'));
        }
        return $this->redirect(['action' => 'index']);
    }

    function doOperation() {
//        debug($this->request->data);
//        exit;
        $ids = $this->request->data['chk'];
        $operation = $this->request->data['operation'];
        if ($operation == 'delete') {
            if ($this->Users->deleteAll(['Users.id IN' => $ids])) {
                $this->Flash->success(__('Users deleted successfully'));
            } else {
                $this->Flash->error(__('Users can not be deleted'));
            }
        }
        $this->redirect(array('action' => 'index'));
    }

}

src/Template/Admin/Users/add.ctp
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= __('Add User') ?></h3>
            </div>
            <div class="panel-body">
                <?= $this->Form->create($uuser) ?>
                <?php
                echo $this->Form->input('id');
                ?>
                <?php
                echo $this->Form->input('username', ['class' => 'form-control']);
                echo $this->Form->input('password', ['class' => 'form-control', 'placeholder' => '*******']);
                echo $this->Form->input('passwd', ['class' => 'form-control', 'placeholder' => '*******', 'label' => __('Confirm password')]);
                echo $this->Form->input('group_id', ['class' => 'form-control']);
                ?>
                <div class="Writers hide">
                    <?php echo $this->Form->input('writer_id', array('options' => $writers, 'class' => 'form-control', 'empty' => __('Choose Writer'))); ?>

                </div> 

                <?= $this->Form->button(__('Submit')) ?>
                <?= $this->Form->end() ?>
            </div>
        </div>
    </div>
</div>
<?php echo $this->append('script'); ?>
<script>
    $(function () {
        $('#group-id').on('change', function () {
            if ($(this).val() == '5') {
                $('.Writers').removeClass('hide').show();
                $('.Writers select').removeProp('disabled');
            } else {
                $('.Writers').addClass('hide').hide();
                $('.Writers select').prop('disabled', 'disabled');
            }
        }).trigger('change');
    })
</script>
<?php echo $this->end(); ?>

src/Template/Admin/Users/edit.ctp
<div class="users form large-9 medium-8 columns content">
    <?= $this->Form->create($user) ?>
    <fieldset>
        <legend><?= __('Edit User') ?></legend>
        <?php
        echo $this->Form->input('username', ['class' => 'form-control']);
        echo $this->Form->input('password', ['class' => 'form-control']);
        echo $this->Form->input('role', ['class' => 'form-control']);
        ?>
    </fieldset>
    <?= $this->Form->button(__('Submit'),['class'=>'btn btn-primary']) ?>
    <?= $this->Form->end() ?>
</div>

src/Template/Admin/Users/index.ctp
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= __('Users') ?></h3>
            </div>
            <div class="panel-body">
                <!--Table Wrapper Start-->
                <form action="<?php echo $this->Url->build(array("action" => "do-operation")) ?>" method="post">
                    <div class="table-responsive ls-table">
                        <table class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th><input type="checkbox" name="checkall" /></th>
                                    <th><?= $this->Paginator->sort('username') ?></th>

                                    <th><?= $this->Paginator->sort('group_id', __('Group')) ?></th>
                                    <th><?= $this->Paginator->sort('created') ?></th>
                                    <!--<th><?= $this->Paginator->sort('updated') ?></th>-->
                                    <th class="actions"><?= __('Actions') ?></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                foreach ($uusers as $uuser):
//                                debug($uuser);
                                    ?>
                                    <tr>
                                        <td><input  type="checkbox" name="chk[]" value="<?php echo $uuser->id ?>" /></td>
                                        <td><?= h($uuser->username) ?></td>

                                        <td><?= $uuser->has('group') ? $uuser->group->name : '' ?></td>
                                        <td><?= h($uuser->created) ?></td>
                                        <!--<td><?= h($uuser->updated) ?></td>-->
                                        <td class="actions">
                                            <?= $this->Html->link('<i class="fa fa-pencil"></i> ' . __('Edit'), ['action' => 'edit', $uuser->id], ['class' => 'btn btn-primary', 'escape' => false]) ?>
                                            <?= $this->Form->postLink('<i class="fa fa-trash"></i> ' . __('Delete'), ['action' => 'delete', $uuser->id], ['class' => 'btn btn-danger', 'escape' => false, 'confirm' => __('Are you sure you want to delete # {0}?', $uuser->username)]) ?>


                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                        <div class="row">
                            <div class="col-md-3">
                                <select class="form-control" id="acts" name="operation">
                                    <option value="">
                                        <?php echo __("Choose Operation") ?></option>
                                    <option value="delete"><?php echo __("Delete") ?></option>
                                </select>
                            </div>
                            <div class="col-md-9 text-right">
                                <ul class="pagination ls-pagination">
                                    <?php
                                    if ($this->Paginator->hasPrev()) {
                                        echo $this->Paginator->prev('< ' . __('previous'));
                                    }
                                    echo $this->Paginator->numbers();
                                    if ($this->Paginator->hasNext()) {
                                        echo $this->Paginator->next(__('next') . ' >');
                                    }
                                    ?>
                                </ul>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

src/Template/Admin/Users/login.ctp
<?php
/**
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @since         0.10.0
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */
$this->assign('title', $title_for_layout);
?>
<!DOCTYPE html>
<html>
    <head>
        <?php echo $this->Html->charset() ?>
        <!-- Viewport metatags -->
        <meta name="HandheldFriendly" content="true" />
        <meta name="MobileOptimized" content="320" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <title>

            <?php echo $this->fetch('title') ?>
        </title>
        <?php echo $this->Html->meta('icon') ?>
        <?php echo $this->fetch('meta') ?>

        <?php
        if ($lang == 'ar') {
            echo $this->Html->css(array('admin/rtl-css/bootstrap-rtl', 'admin/rtl-css/style-rtl', 'admin/rtl-css/responsive-rtl'));
        } else {
            echo $this->Html->css(array('admin/bootstrap.min', 'admin/style', 'admin/responsive'));
        }

        echo $this->Html->css(array('admin/plugins/pace', 'admin/plugins/ladda-themeless.min',
            'admin/plugins/humane_themes/bigbox', 'admin/plugins/humane_themes/libnotify', 'admin/plugins/humane_themes/jackedup'))
        ?>
        <?php echo $this->Html->script(array('admin/pace.min')) ?>
        <?php echo $this->fetch('css') ?>

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->


    </head>
    <body class="login-screen">
        <section>
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="login-box">
                            <div class="login-content">

                                <?php // echo $this->Html->image('admin/logo-1.png'); ?>



                            </div>

                            <div class="login-form">
                                <?php
                                echo $this->Flash->render();
                                $this->Form->templates(['inputContainer' => '{{content}}']);
                                ?>
                                <?php echo $this->Form->create('Users', ['url' => '/admin', 'class' => 'form-horizontal ls_form', 'id' => 'form-login']); ?>
                                <!--<form id="form-login" action="<?php echo $this->Url->build() ?>" class="form-horizontal ls_form">-->
                                <div class="input-group ls-group-input">
                                    <?php echo $this->Form->input('username', ['label' => false, 'class' => 'form-control', 'placeholder' => __('Username', true)]) ?>
                                    <span class="input-group-addon"><i class="fa fa-user"></i></span>
                                </div>


                                <div class="input-group ls-group-input">

                                    <?php echo $this->Form->input('password', ['label' => false, 'class' => 'form-control', 'placeholder' => __('Password', true)]) ?>
                                    <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                                </div>


                                <div class="input-group ls-group-input login-btn-box">
                                    <button type="submit" class="btn ls-dark-btn ladda-button col-md-12 col-sm-12 col-xs-12" ty data-style="slide-down">
                                        <span class="ladda-label"><i class="fa fa-key"></i></span>
                                    </button>

                                    <a class="forgot-password" href="javascript:void(0)"><?php echo __('Forgot password')?></a>
                                </div>
                                </form>
                            </div>
                            <div class="forgot-pass-box">
                                <form action="#" class="form-horizontal ls_form">
                                    <div class="input-group ls-group-input">
                                        <input class="form-control" type="text" placeholder="someone@mail.com">
                                        <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
                                    </div>
                                    <div class="input-group ls-group-input login-btn-box">
                                        <button class="btn ls-dark-btn col-md-12 col-sm-12 col-xs-12">
                                            <i class="fa fa-rocket"></i> Send
                                        </button>

                                        <a class="login-view" href="javascript:void(0)"><?php echo __('Login')?></a>

                                    </div>
                                </form>
                            </div>

                        </div>
                    </div>
                </div>
            </div>

        </section>
        <?php
        echo $this->Html->script(array('admin/lib/jquery-2.1.1.min', 'admin/bootstrap.min.js', 'admin/lib/jquery.easing.js',
            'admin/loader/spin.js', 'admin/loader/ladda.js', 'admin/humane.min.js', 'admin/pages/login'))
        ?>
        <?php echo $this->fetch('script') ?>
    </body>
</html>

src/Template/Admin/Users/view.ctp
<nav class="large-3 medium-4 columns" id="actions-sidebar">
    <ul class="side-nav">
        <li class="heading"><?= __('Actions') ?></li>
        <li><?= $this->Html->link(__('Edit User'), ['action' => 'edit', $uuser->id]) ?> </li>
        <li><?= $this->Form->postLink(__('Delete User'), ['action' => 'delete', $uuser->id], ['confirm' => __('Are you sure you want to delete # {0}?', $uuser->id)]) ?> </li>
        <li><?= $this->Html->link(__('List Users'), ['action' => 'index']) ?> </li>
        <li><?= $this->Html->link(__('New User'), ['action' => 'add']) ?> </li>
    </ul>
</nav>
<div class="users view large-9 medium-8 columns content">
    <h3><?= h($uuser->username) ?></h3>
    <table class="vertical-table">
        <tr>
            <th><?= __('Username') ?></th>
            <td><?= h($uuser->username) ?></td>
        </tr>
        <tr>
            <th><?= __('Password') ?></th>
            <td><?= h($uuser->password) ?></td>
        </tr>
        <tr>
            <th><?= __('Role') ?></th>
            <td><?= h($uuser->role) ?></td>
        </tr>
        <tr>
            <th><?= __('Id') ?></th>
            <td><?= $this->Number->format($uuser->id) ?></td>
        </tr>
        <tr>
            <th><?= __('Created') ?></th>
            <td><?= h($uuser->created) ?></td>
        </tr>
        <tr>
            <th><?= __('Updated') ?></th>
            <td><?= h($uuser->updated) ?></td>
        </tr>
    </table>
</div>